[ADD] Adding new module partner_identification_sim_indonesia
open-synergy/opnsynid-l10n-indonesia pull request #1
Opened 2016-12-19 10:35 UTC by mikevhe18

2016-12-20 00:25 UTC, andhit-r requested changes
Mike kok .pyc nya ikut ke ambil?

2016-12-20 10:09 UTC, andhit-r requested changes

2016-12-20 10:09 UTC, andhit-r commented on partner_identification_sim_indonesia/models/res_partner_id_number.py
> +    _sql_constraints = [
@mikevhe18 validasinya bukan begitu caranya. Coba lihat https://github.com/OCA/partner-contact/pull/298/files#diff-55ffa8353f7b2918117e842a9334d86cR7 dan https://github.com/OCA/partner-contact/pull/298/files#diff-51ed1038dbdf198d833c2475bad80d56R30

2016-12-21 01:12 UTC, mikevhe18 commented on partner_identification_sim_indonesia/models/res_partner_id_number.py
> +    _sql_constraints = [
Iya mas gue tau, tapi masalahnya : 
1. Validation itu khan opsional , bisa dipake bisa ngga
2. Validasi yang di contoh itu buat GLN dimana emang ada validasi check digit, sementara SIM dari apa yang gw cari referensinya gak ada validasi check digit
3. Trus untuk fungsi search duplicatenya, menurut gw cukup pake SQL constraints

2016-12-21 04:10 UTC, andhit-r commented
Superseded by #2 . Closing.

2016-12-21 04:10 UTC, closed without merging